#/bin/bash

brew update
brew install autoconf
brew install awscli
brew install brotli
brew install c-ares
brew install ca-certificates
brew install cairo
brew install cffi
brew install docker
brew install docker-compose
brew install docutils
brew install fontconfig
brew install freetype
brew install gdbm
brew install gettext
brew install giflib
brew install glib
brew install gmp
brew install gnutls
brew install go
brew install golang-migrate
brew install graphite2
brew install harfbuzz
brew install icu4c
brew install jpeg-turbo
brew install kubernetes-cli
brew install libcbor
brew install libevent
brew install libfido2
brew install libgcrypt
brew install libgpg-error
brew install libidn2
brew install libmaxminddb
brew install libnghttp2
brew install libpng
brew install libpthread-stubs
brew install libsmi
brew install libssh
brew install libtasn1
brew install libtiff
brew install libunistring
brew install libuv
brew install libx11
brew install libxau
brew install libxcb
brew install libxdmcp
brew install libxext
brew install libxrender
brew install little-cms2
brew install llvm
brew install lua
brew install lz4
brew install lzo
brew install m4
brew install macos-term-size
brew install minikube
brew install mongodb-community
brew install mongodb-database-tools
brew install mongosh
brew install mpdecimal
brew install mysql
brew install nettle
brew install node@14
brew install node@16
brew install node@18
brew install nvm
brew install openssl@1.1
brew install openssl@3
brew install p11-kit
brew install pcre2
brew install pixman
brew install pkg-config
brew install protobuf
brew install protobuf@21
brew install pycparser
brew install pyenv
brew install python@3.10
brew install python@3.11
brew install readline
brew install six
brew install sqlc
brew install sqlite
brew install unbound
brew install xorgproto
brew install xz
brew install z3
brew install zlib
brew install zstd
brew install adobe-acrobat-reader
brew install anaconda
brew install dbeaver-community
brew install docker
brew install firefox-developer-edition
brew install iterm2
brew install mongodb-compass
brew install mysqlworkbench
brew install postman
brew install powershell
brew install pycharm-ce
brew install skype
brew install stats
brew install vagrant
brew install visual-studio-code
brew install zeplin
