choco install atom -y
choco install atom.install -y
choco install awscli -y
choco install chocolatey -y
choco install chocolatey-core.extension -y
choco install chocolatey-dotnetfx.extension -y
choco install chocolatey-visualstudio.extension -y
choco install chocolatey-windowsupdate.extension -y
choco install docker-desktop -y
choco install dotnetfx -y
choco install golang -y
choco install gradle -y
choco install intellijidea-community -y
choco install KB2919355 -y
choco install KB2919442 -y
choco install KB2999226 -y
choco install KB3033929 -y
choco install KB3035131 -y
choco install kubernetes-cli -y
choco install mingw -y
choco install Minikube -y
choco install nodejs-lts -y
choco install openjdk -y
choco install postman -y
choco install pycharm-community -y
choco install python -y
choco install python3 -y
choco install vagrant -y
choco install vcredist140 -y
choco install vcredist2015 -y
choco install visualstudio-installer -y
choco install visualstudio2017buildtools -y
